accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.RegistrationView.as_view(), name="register"),
    path('login/',views.LoginView.as_view(), name="login"),
    path('logout/',views.LogoutView.as_view(), name="logout"),
    path('password_change/', views.PasswordChangeView.as_view(), name="password_change"),
    path('password_reset/', views.PasswordResetView.as_view(), name="password_reset")
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('course/search/', views.SearchResultsView, name='search'),
    path('course/details/<int:pk>/', views.CourseDetailView.as_view(), name='details'),
    path('course/reserve/<int:cid>/<int:lid>/', views.course_reserve, name='reserve'),
    path('course/cancel/<int:cid>/<int:lid>/', views.course_cancel, name='course-cancel'),
    path('course/teach/<pk>', views.course_teach, name='teach'),
    
    # path('student/profile/create', views.StudentCreateView.as_view(), name="student-profile-create"),
    # path('lecturer/profile/create', views.LecturerCreateteView.as_view(), name="lecturer-profile-create"),
    path('lecturer/profile/<pk>', views.LecturerView.as_view(), name="lecturer-profile"),
    path('lecturer/profile/update/<pk>', views.LecturerUpdateView.as_view(), name="lecturer-profile-update"),

    path('student/profile/<pk>', views.StudentView.as_view(), name="student-profile"),
    path('student/profile/update/<pk>', views.StudentUpdateView.as_view(), name="student-profile-update"),
    path('student/progress/', views.progress, name="progress"),
    path('student/certification/<int:cid>/<int:lid>', views.certificate_generation, name="certify"),
    # path('student/attendance/', views.attendance, name="attendance"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),

]

core/urls.py
from django import contrib
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>{%block title%}{% endblock %}</title>
  {%block meta-data %}{% endblock %}
  <link rel="stylesheet" href="{% static 'accounts/bootstrap/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/base-style.css' %}" />
  <script src="{%static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'accounts/bootstrap/js/bootstrap.min.js' %}"></script>
</head>

<body>
  <header class="p-2 bg-dark bg-gradient text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'app:home' %}">
          <img src="{% static 'accounts/icons/home.png' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white"
            height="50" />
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'app:home' %}" class="nav-link px-2 text-white">Search</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'app:progress' %}" class="nav-link px-2 text-white">
              {% if user.is_superuser %}
              Course Status
              {%else%}
              Progress
              {%endif%}
            </a></li>
          {% endif %}
          <li><a href="{% url 'app:contact' %}" class="nav-link px-2 text-white">Contacts</a></li>
          <li><a href="{% url 'app:about' %}" class="nav-link px-2 text-white">About</a></li>

        </ul>

        <div class="text-end">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            {% if user.is_authenticated %}
            {% if user.is_superuser %}
            <a class="nav-link text-white me-2" href="{% url 'admin:index' %}">Dashboard</a>
            <a class="nav-link text-white me-2" href="{% url 'app:lecturer-profile' user.id %}">{{user.first_name}}</a>

            {% elif user.is_staff %}
            <a class="nav-link text-white me-2" href="{% url 'app:lecturer-profile' user.id %}">{{user.first_name}}</a>
            {% else %}
            <a class="nav-link text-white me-2" href="{% url 'app:student-profile' user.id %}">{{user.first_name}}</a>
            {% endif %}
            <a class="nav-link text-white me-2" href="{% url 'accounts:password_change' %}">Change Password</a>
            <a class="btn btn-warning" href="{% url 'accounts:logout' %}">Logout</a>

            {% else %}
            <a class="btn btn-outline-light me-2" href="{% url 'accounts:login' %}">Login</a>
            <a class="btn btn-warning" href="{% url 'accounts:register' %}">Register</a>
            {% endif %}

          </ul>
        </div>
      </div>
    </div>
  </header>
  <div style="margin-bottom: 50px;">
    {%block content%}{%endblock%}
  </div>
</body>
<footer class="footer mt-auto py-3 bg-dark bg-gradient fixed-bottom ">
  <div class="container">
    <div class="row text-center">
      <div class="col-sm-12 text-center">
        <span class="text-white"> <a href="https://github.com/okmd/" class="text-decoration-none text-white">@okmd</a></span><br>
        <span class="text-white">Course Reservation System &copy; 2021 </span>
      </div>
      
    </div>
  </div>
</footer>

</html>