app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('course/search/', views.SearchResultsView, name='search'),
    path('course/details/<int:pk>/', views.CourseDetailView.as_view(), name='details'),
    path('course/reserve/<int:cid>/<int:lid>/', views.course_reserve, name='reserve'),
    path('course/cancel/<int:cid>/<int:lid>/', views.course_cancel, name='course-cancel'),
    path('course/teach/<pk>', views.course_teach, name='teach'),
    
    # path('student/profile/create', views.StudentCreateView.as_view(), name="student-profile-create"),
    # path('lecturer/profile/create', views.LecturerCreateteView.as_view(), name="lecturer-profile-create"),
    path('lecturer/profile/<pk>', views.LecturerView.as_view(), name="lecturer-profile"),
    path('lecturer/profile/update/<pk>', views.LecturerUpdateView.as_view(), name="lecturer-profile-update"),

    path('student/profile/<pk>', views.StudentView.as_view(), name="student-profile"),
    path('student/profile/update/<pk>', views.StudentUpdateView.as_view(), name="student-profile-update"),
    path('student/progress/', views.progress, name="progress"),
    path('student/certification/<int:cid>/<int:lid>', views.certificate_generation, name="certify"),
    # path('student/attendance/', views.attendance, name="attendance"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),

]

core/urls.py
from django import contrib
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from accounts.models import CustomUser
# Create your models here.


class Course(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_name = models.CharField(max_length=200)
    prerequisites = models.ManyToManyField("self", blank=True, symmetrical=False)
    description = models.TextField(blank=True)
    cover = models.ImageField(
        upload_to="courses", default="courses/default.png", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    course_fee = models.IntegerField(default=0)

    def __str__(self):
        return self.course_name

    class Meta:
        db_table = 'courses'


class Catalog(models.Model):
    catalog_id = models.AutoField(primary_key=True)
    catalog_name = models.CharField(max_length=100)
    courses = models.ManyToManyField(Course)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.catalog_name


class BaseProfile(models.Model):
    street_address = models.CharField(max_length=100, default="Street Address")
    locality = models.CharField(max_length=100, default="Locality")
    district = models.CharField(max_length=20, default="District")
    state = models.CharField(max_length=20, default="State")
    pincode = models.IntegerField(default=000000)
    mobile_number = models.CharField(max_length=10, default="0000000000")
    profile_pic = models.ImageField(
        upload_to="profile_images", default="courses/default.png")
    wallet = models.FloatField(default=0)

    class Meta:
        abstract = True


class Lecturer(BaseProfile):
    lecturer = models.OneToOneField(CustomUser, limit_choices_to={
                                    'is_staff': True}, on_delete=models.CASCADE, primary_key=True)
    taught = models.ManyToManyField(Course, blank=True)

    def __str__(self):
        return self.lecturer.email


class Student(BaseProfile):
    student = models.OneToOneField(CustomUser, limit_choices_to={
                                   'is_student': True}, on_delete=models.CASCADE, primary_key=True)
    enrolled = models.ManyToManyField(Course, blank=True)

    def __str__(self):
        return self.student.email


# class BaseInterface(models.Model):
#     course_id = models.ForeignKey(Course, on_delete=models.DO_NOTHING)
#     student_id = models.ForeignKey(Student, on_delete=models.DO_NOTHING)
#     lecturer_id = models.ForeignKey(Lecturer, on_delete=models.DO_NOTHING)
#     class Meta:
#         abstract=True
# class StudentClassStatus(models.TextChoices):
#     PRESENT = 'P'
#     ABSENT = 'A'
# class Attendance(BaseInterface):
#     status = models.CharField(choices=StudentClassStatus.choices, max_length=10)
#     class_date = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f'{self.course_id}-{self.student_id}-{self.lecturer_id}'

class StudentGradeChoices(models.TextChoices):
    A = 'A'
    B = 'B'
    C = 'C'
    F = 'F'
class Progress(models.Model):
    course_id = models.ForeignKey(Course, on_delete=models.DO_NOTHING)
    student_id = models.ForeignKey(Student, on_delete=models.DO_NOTHING)
    lecturer_id = models.ForeignKey(Lecturer, on_delete=models.DO_NOTHING)
    progress = models.IntegerField(default=0)
    # certified = models.BooleanField(default=False)
    course_fee = models.IntegerField(default=0)
    grade = models.CharField(choices=StudentGradeChoices.choices, max_length=10, blank=True)
    completion_date = models.DateField(blank=True, null=True)
    enrollment_date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = (('course_id', 'student_id', 'lecturer_id'),)

    def __str__(self):
        return f'{self.course_id}-{self.student_id}-{self.lecturer_id}'
    

app/templates/app/about.html
{% extends '../base.html' %}
{% load static %}
{%block title %}About{% endblock %}
{%block content %}
<div class="container text-center" style="margin-top: 100px;">
    <h3 class="display-3 mt-3">Course Reservation System</h3>
    <p class="m-3">
        Hey!, I am Mohammad Danish, M.tech student at Delhi Technological University at the department of Software
        Engineering.
    </p>
    <div class="">
        <!-- Facebook -->
        <a class="btn btn-primary" style="background-color: #3b5998;" href="http://github.com/okmd" role="button"><i
                class="fa fa-github"></i></a>

        <!-- Twitter -->
        <a class="btn btn-primary" style="background-color: #55acee;" href="https://www.linkedin.com/in/okmd"
            role="button"><i class="fa fa-linkedin"></i></a>

        <a class="btn btn-primary" style="background-color: #55acee;" href="https://leetcode.com/okmd/" role="button"><i
                class="fa fa-code"></i></a>

        <p class="text-center mt-1">
            Follow me
        </p>
    </div>
</div>
{%endblock%}

app/templates/app/create-profile.html
{% extends '../base.html' %}
{% load static %}
{%block title %}Create Profile{% endblock %}
{%block content %}
<div class="container">
    <div style="width: 400px; margin: auto;">
        <main class="form-log-sign">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.errors}}

                <h1 class="h3 m-3 fw-normal text-center">Create Your profile</h1>
                <div class="form-floating">
                    {{form.student}}
                    <label for="id_student">Student</label>
                    <span class="text-danger">{{form.student.errors}}</span>
                </div>
                <div class="form-floating">
                    {{form.lecturer}}
                    <label for="id_student">Lecturer</label>
                    <span class="text-danger">{{form.lecturer.errors}}</span>
                </div>

                <div class="form-floating">
                    {{form.street_address}}
                    <label for="id_stree_addess">Street Address</label>
                    <span class="text-danger">{{form.stree_addesss.errors}}</span>
                </div>
                <div class="form-floating">
                    {{form.locality}}
                    <label for="id_locality">Locality</label>
                    <span class="text-danger">{{form.locality.errors}}</span>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-floating">
                            {{form.district}}
                            <label for="id_district">District</label>
                            <span class="text-danger">{{form.district.errors}}</span>
                        </div>
                    </div>
                    
                    <div class="col-sm-6">
                        <div class="form-floating">
                            {{form.state}}
                            <label for="id_state">State</label>
                            <span class="text-danger">{{form.state.errors}}</span>
                        </div>
                    </div>
                </div>
                
                <div class="form-floating">
                    {{form.pincode}}
                    <label for="id_pincode">Pincode</label>
                    <span class="text-danger list-item">{{form.picode.errors}}</span>
                </div>
                <div class="form-floating">
                    {{form.mobile_number}}
                    <label for="id_mobile_number">Mobile Number</label>
                    <span class="text-danger list-item">{{form.mobile_number.errors}}</span>
                </div>
                <div class="mb-3">
                    {{form.profile_pic}}
                    <span class="text-danger list-item">{{form.profile_pic.errors}}</span>
                </div>
                <hr>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Update</button>
            </form>
    </div>
</div>
{%endblock%}

app/templates/app/details.html
{% extends 'base.html' %}
{% load static %}

{%block title %}Details of course{% endblock %}
{% block content %}
<div class="container col-xxl-8 px-2 py-2">
  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
    <div class="col-10 col-sm-8 col-lg-6">
      <img src="{{object.cover.url}}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700"
        height="500" loading="lazy">
    </div>
    <div class="col-lg-6">
      <h1 class="display-5 fw-bold lh-1 mb-3">{{object.course_name}}</h1>
      <p class="lead">
        {{object.description}}<br>
      <p>Course Fee <b class="m-1">₹ {{object.course_fee}}</b></p>
      <hr>
      <spna class="text-muted">Prerequites:</spna>
      {% if course.prerequisites.all %}
      {% for pre in course.prerequisites.all %}
      <a href="{% url 'app:details' pre.pk %}">{{pre}}</a>
      {% endfor %}
      {% else %}
      No prerequisites.
      {% endif %}
      </p>
      <div class="d-grid gap-2 justify-content-md-start">
        {% if user.is_staff %}
        <a class="btn btn-success btn-lg px-4 me-md-2" href="{% url 'app:teach' object.pk %}">Teach</a>
        {% else %}
        <!-- need to change to provide lid not sid  -->
        {%if lecturers %}
        <p class="text-success">This course is available from these Lecturers:</p>
        {% for lec in lecturers %}
        <div class="row">
          <div class="col-sm-6">
            <b>{{lec.lecturer.first_name}} {{lec.lecturer.last_name}}</b>
          </div>
          <div class="col-sm-6">
            <a class="btn btn-success btn-lg px-4 me-md-2" href="{% url 'app:reserve' object.pk lec.pk %}">Reserve</a>
          </div>
        </div>
        {% endfor %}

        {%endif%}

        {% endif %}
      </div>
    </div>
  </div>
  {% if messages %}
  <ul class="messages mb-3">
    {% for message in messages %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}</strong>
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endblock %}

app/templates/app/index.html
{% extends 'base.html' %}
{% load static %}

{%block title %}Welcome{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="display-5 fw-bold p-5 text-center">Welcome to online course reservation system</h1>
    </div>
  </div>
  <div class="row justify-content-md-center p-5">
    <div class="col-sm-6">
      <h3 class="text-center">Find your course</h3>
      <form action="{% url 'app:search' %}" method="GET">
       

        <div class="input-group">
          <input type="search" name="query" class="form-control rounded p-3" placeholder="Course title/description" required autofocus/>
    
          <button type="submit" class="btn btn-outline-primary">search</button>
        </div>
        <div class="form-check mt-3 form-check-inline">
          <input class="form-check-input" type="checkbox" id="flexCheckDefault" name="catalog">
          <label class="form-check-label" for="flexCheckDefault">Do you want to search catalog?</label>
        </div>
      </form>

    </div>
  </div>

</div>
{% endblock %}

app/templates/app/profile.html
{% extends '../base.html' %}
{% load static %}
{%block title %}Profile{% endblock %}
{%block content %}
<div class="container" style="margin-bottom: 100px;">
    <div class="row m-3">
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center"> <img
                            src="{{object.profile_pic.url}}" alt="Profile image" class="rounded-circle" width="150">
                        <div class="mt-3">
                            {% if object.student %}
                            <h4>{{object.student.first_name}} {{object.student.last_name}}</h4>
                            <p class="text-center">Student</p>
                            <p class="text-secondary mb-1">
                                {{object.student.email}}
                                <br>
                                Wallet:<b> ₹ {{object.wallet}}</b>
                            </p>
                            {% elif object.lecturer %}
                            <h4>{{object.lecturer.first_name}} {{object.lecturer.last_name}}</h4>
                            <p class="text-center">Lecturer</p>
                            <p class="text-secondary mb-1">
                                {{object.lecturer.email}}
                                <br>
                                Wallet:<b> ₹ {{object.wallet}}</b>
                            </p>
                            {% endif %}

                            <p class="text-secondary mb-1">
                                {{object.mobile_number}}
                            </p>
                            <p class="text-secondary mb-1">
                                {{object.street_address}},
                                {{object.locality}},
                                {{object.district}},
                                {{object.state}}-
                                {{object.pincode}}
                            </p>
                            {% if object.student %}
                            <a class="btn btn-primary mt-3"
                                href="{% url 'app:student-profile-update' object.pk %}">Update Profile</a>
                            {% else %}
                            <a class="btn btn-primary mt-3"
                                href="{% url 'app:lecturer-profile-update' object.pk %}">Update Profile</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">

            {% if object.enrolled %}
            <h2 class="text-center m-2">Courses Enrolled</h2>
            {% if messages %}
            <ul class="messages mt-3">
                {% for message in messages %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}</strong>
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="row">
                {% for course in courses.all %}
                <div class="card m-1 col-md-5">
                    <div class="card-body">
                        <h5 class="card-title">{{course.course_id.course_name}}</h5>
                        <hr>
                        <p class="card-text">
                        <p class="text-dark">A course from:<b> {{course.lecturer_id.lecturer.first_name}}
                                {{course.lecturer_id.lecturer.last_name}}</b>
                            @ <b>₹ {{course.course_fee}}</b> </p>
                        {% if course.course_id.prerequisites.all %}
                        {% for pre in course.course_id.prerequisites.all %}
                        <a href="{% url 'app:details' pre.pk %}">{{pre}}</a>
                        {% endfor %}
                        {% else %}
                        No prerequisites.
                        {% endif %}

                        </p>
                        <a href="{% url 'app:details' course.course_id.pk %}" class="btn btn-info">Details</a>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <h2 class="text-center m-2">Courses Taught</h2>
            <div class="row">


                {% for course in object.taught.all %}


                <div class="card m-1 col-md-5">
                    <div class="card-body">
                        <h5 class="card-title">{{course.course_name}}</h5>
                        <hr>
                        <p class="card-text">
                        <p class="text-dark">Course Fee : <b>₹ {{course.course_fee}}</b></p>
                        {% if course.prerequisites.all %}
                        {% for pre in course.prerequisites.all %}
                        <a href="{% url 'app:details' pre.pk %}">{{pre}}</a>
                        {% endfor %}
                        {% else %}
                        No prerequisites.
                        {% endif %}
                        </p>
                        <a href="{% url 'app:details' course.pk %}" class="btn btn-info">Details</a>
                    </div>
                </div>

                {% endfor %}
            </div>
            {% endif %}



        </div>
    </div>
</div>
{%endblock%}

app/templates/app/progress.html
{% extends '../base.html' %}
{% load static %}
{%block title %}Progress{% endblock %}
{%block content %}
<div class="container">
    <div class="row m-3">

        <div class="row">
            {% if user.is_staff %}
            <h2 class="text-center m-3">Course Status</h2>
            {% for p, sub_p in progress %}
            <div class="col-sm-4">
                <div class="card shadow-sm">

                    <div class="text-center">
                        <img src="{{p.cover.url}}" class="img-thumbnail" />
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title"><a href="{% url 'app:details' p.course_id %}"
                                class="text-decoration-none"> {{p.course_name}} </a></h5>
                        <p class="card-text">
                            <b>Total registrations: {{sub_p.count}}.<br>
                                Total Earnings = ₹ {{sub_p.earning}}.<br>
                            </b>
                        </p>

                    </div>
                </div>
            </div>
            {% endfor %}
            <p class="text-center m-3">NOTE: Course Progress will be visible only if student register for you courses.
            </p>
            {% else %}
            <h2 class="text-center m-3">Course Progress</h2>
            {% for p in progress %}
            <div class="col-sm-4">
                <div class="card mb-1">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'app:details' p.course_id.pk %}"
                                class="text-decoration-none"> {{p.course_id.course_name}} </a></h5>
                        <p class="card-text">
                            A course from <b>{{p.lecturer_id.lecturer.first_name}}
                                {{p.lecturer_id.lecturer.last_name}}</b><br>
                            Course Fee = ₹ {{p.course_fee}}<br>
                            Enrollment Date = {{p.enrollment_date}}.<br>
                        </p>

                        <div class="float-left">
                            <div class="progress mb-2">
                                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="{{p.progress}}"
                                    aria-valuemin="0" aria-valuemax="100" style="width:{{p.progress}}%">{{p.progress}}%
                                    Complete</div>
                            </div>
                            {% if p.progress == 100 %}
                            <p class="text-success">You have successfully completed this course on {{p.completion_date}}
                                with grade {{p.grade}}.</p>
                            <a class="btn btn-success"
                                href="{% url 'app:certify' p.course_id.pk p.lecturer_id.pk %}">Generate Certificate</a>

                            {%else%}
                            <p class="text-danger">Course Not Complete</p>
                            <a class="btn btn-danger"
                                href="{% url 'app:course-cancel' p.course_id.pk p.lecturer_id.pk %}">Cancel
                                Enrollment</a>

                            {% endif %}


                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
            {% if messages %}
            <ul class="messages mt-3">
                {% for message in messages %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}</strong>
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{%endblock%}

app/templates/app/search.html
{% extends 'base.html' %}
{% load static %}

{%block title %}Search Courses and Catalogs{% endblock %}
{% block content %}

<div class="container py-2">
    <div class="album">
        <div class="container">
            {% if count %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% if user.is_staff %}
                {% for course in courses %}
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-header text-center mb-3">{{course.course_name}}</div>
                        <div class="text-center">
                            <img src="{{ course.cover.url }}" class="img-thumbnail" />
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{course.description|truncatewords:"50"}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a class="btn btn-success" href="{% url 'app:teach' course.pk %}">Teach</a>
                                <b class="text-center">₹ {{course.course_fee}}</b>
                                <a class="btn btn-info" href="{% url 'app:details' course.pk %}">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                {% for course, faculty in courses %}
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-header text-center mb-3">{{course.course_name}}</div>
                        <div class="text-center" >
                            <img src="{{ course.cover.url }}" class="img-thumbnail" />
                        </div>
                        <div class="card-body">
                            <p class="text-center m-3">Course From: <b> {{faculty.1}} {{faculty.2}} @ ₹
                                    {{course.course_fee}}</b></p>
                            <p class="card-text">{{course.description|truncatewords:"50"}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a class="btn btn-success"
                                    href="{% url 'app:reserve' course.pk faculty.0 %}">Reserve</a>
                                <a class="btn btn-info" href="{% url 'app:details' course.pk %}">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            {% elif request.GET.catalog != 'on' %}
            <p class="text-danger display-5 text-center"> There is no course matching with given search query.</p>
            {% endif %}
        </div>
    </div>

    <!-- catalog -->
    <div class="album">
        {% if catalogs %}
        <h5 class="display-5 text-center mb-2"> List of catalogs with courses</h5>
        <div class="accordion" id="accordionFlushExample">
            {% for catalog in catalogs %}
            <div class="accordion-item mb-1">
                <h2 class="accordion-header" id="{{catalog.pk}}" d="{% cycle 'a' 'b' %}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-{{catalog.pk}}" aria-expanded="false"
                        aria-controls="flush-{{catalog.pk}}">
                        Catalog : {{catalog.catalog_name}}
                    </button>
                </h2>
                <div id="flush-{{catalog.pk}}" class="accordion-collapse collapse" aria-labelledby="{{catalog.pk}}"
                    data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        {% for course in catalog.courses.all %}
                        <div class="card mb-1">
                            <div class="card-body d-flex flex-wrap align-items-center">
                                <div style="width: 50px;" class="m-3">
                                    <img src="{{course.cover.url}}" class="img-fluid float-start m-1">
                                </div>
                                <div>{{course.course_name}}</b> @ ₹ {{course.course_fee}}</div>

                                <div style="margin-left: auto;"><a href="{%url 'app:details' course.pk %}"
                                        class="btn btn-info">Details</a></div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {%elif request.GET.catalog == 'on' %}
            <p class="text-danger display-5 text-center"> There is no catalog matching with given search query.</p>
            {% endif %}
    </div>
</div>
    {% endblock %}

app/templates/app/update-profile.html
{% extends '../base.html' %}
{% load static %}
{%block title %}UPdate Student Profile{% endblock %}
{%block content %}
<div class="container">
    <div style="width: 400px; margin: auto;">
        <main class="form-log-sign">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <h1 class="h3 m-3 fw-normal text-center">Update Your profile</h1>
                <div class="form-floating">
                    {{form.student}}
                    <label for="id_student">Student</label>
                    <span class="text-danger">{{form.student.errors}}</span>
                </div>
                <div class="form-floating">
                    {{form.lecturer}}
                    <label for="id_student">Lecturer</label>
                    <span class="text-danger">{{form.lecturer.errors}}</span>
                </div>

                <div class="form-floating">
                    {{form.street_address}}
                    <label for="id_stree_addess">Street Address</label>
                    <span class="text-danger">{{form.stree_addesss.errors}}</span>
                </div>
                <div class="form-floating">
                    {{form.locality}}
                    <label for="id_locality">Locality</label>
                    <span class="text-danger">{{form.locality.errors}}</span>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-floating">
                            {{form.district}}
                            <label for="id_district">District</label>
                            <span class="text-danger">{{form.district.errors}}</span>
                        </div>
                    </div>
                    
                    <div class="col-sm-6">
                        <div class="form-floating">
                            {{form.state}}
                            <label for="id_state">State</label>
                            <span class="text-danger">{{form.state.errors}}</span>
                        </div>
                    </div>
                </div>
                
                <div class="form-floating">
                    {{form.pincode}}
                    <label for="id_pincode">Pincode</label>
                    <span class="text-danger list-item">{{form.picode.errors}}</span>
                </div>
                <div class="form-floating">
                    {{form.mobile_number}}
                    <label for="id_mobile_number">Mobile Number</label>
                    <span class="text-danger list-item">{{form.mobile_number.errors}}</span>
                </div>
                <div class="form-floating">
                    {{form.wallet}}
                    <label for="id_wallet">Wallet</label>
                    <span class="text-danger list-item">{{form.wallet.errors}}</span>
                </div>
                <div class="mb-3">
                    {{form.profile_pic}}
                    <span class="text-danger list-item">{{form.profile_pic.errors}}</span>
                </div>
                <hr>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Update</button>
            </form>
    </div>
</div>
{%endblock%}